import { forwardRef } from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";
import "./keenicons/styles.bundle.css";

const iconVariants = cva("", {
  variants: {
    style: {
      Duotone: "ki-duotone",
      Filled: "ki-filled",
      Outline: "ki-outline",
      Solid: "ki-solid",
    },
    icon: {
      "Abstract 1": "ki-abstract-1",
      "Abstract 2": "ki-abstract-2",
      "Abstract 3": "ki-abstract-3",
      "Abstract 4": "ki-abstract-4",
      "Abstract 5": "ki-abstract-5",
      "Abstract 6": "ki-abstract-6",
      "Abstract 7": "ki-abstract-7",
      "Abstract 8": "ki-abstract-8",
      "Abstract 9": "ki-abstract-9",
      "Abstract 10": "ki-abstract-10",
      "Abstract 11": "ki-abstract-11",
      "Abstract 12": "ki-abstract-12",
      "Abstract 13": "ki-abstract-13",
      "Abstract 14": "ki-abstract-14",
      "Abstract 15": "ki-abstract-15",
      "Abstract 16": "ki-abstract-16",
      "Abstract 17": "ki-abstract-17",
      "Abstract 18": "ki-abstract-18",
      "Abstract 19": "ki-abstract-19",
      "Abstract 20": "ki-abstract-20",
      "Abstract 21": "ki-abstract-21",
      "Abstract 22": "ki-abstract-22",
      "Abstract 23": "ki-abstract-23",
      "Abstract 24": "ki-abstract-24",
      "Abstract 25": "ki-abstract-25",
      "Abstract 26": "ki-abstract-26",
      "Abstract 27": "ki-abstract-27",
      "Abstract 28": "ki-abstract-28",
      "Abstract 29": "ki-abstract-29",
      "Abstract 30": "ki-abstract-30",
      "Abstract 31": "ki-abstract-31",
      "Abstract 32": "ki-abstract-32",
      "Abstract 33": "ki-abstract-33",
      "Abstract 34": "ki-abstract-34",
      "Abstract 35": "ki-abstract-35",
      "Abstract 36": "ki-abstract-36",
      "Abstract 37": "ki-abstract-37",
      "Abstract 38": "ki-abstract-38",
      "Abstract 39": "ki-abstract-39",
      "Abstract 40": "ki-abstract-40",
      "Abstract 41": "ki-abstract-41",
      "Abstract 42": "ki-abstract-42",
      "Abstract 43": "ki-abstract-43",
      "Abstract 44": "ki-abstract-44",
      "Abstract 45": "ki-abstract-45",
      "Abstract 46": "ki-abstract-46",
      "Abstract 47": "ki-abstract-47",
      "Abstract 48": "ki-abstract-48",
      "Abstract 49": "ki-abstract-49",
      Abstract: "ki-abstract",
      AddFiles: "ki-add-files",
      AddFolder: "ki-add-folder",
      AddNotepad: "ki-add-notepad",
      Additem: "ki-additem",
      AddressBook: "ki-address-book",
      AirplaneSquare: "ki-airplane-square",
      Airplane: "ki-airplane",
      Airpod: "ki-airpod",
      Android: "ki-android",
      Angular: "ki-angular",
      Apple: "ki-apple",
      ArchiveTick: "ki-archive-tick",
      Archive: "ki-archive",
      ArrowCircleLeft: "ki-arrow-circle-left",
      ArrowCircleRight: "ki-arrow-circle-right",
      ArrowDownLeft: "ki-arrow-down-left",
      ArrowDownRefraction: "ki-arrow-down-refraction",
      ArrowDownRight: "ki-arrow-down-right",
      ArrowDown: "ki-arrow-down",
      ArrowLeft: "ki-arrow-left",
      ArrowMix: "ki-arrow-mix",
      ArrowRightLeft: "ki-arrow-right-left",
      ArrowRight: "ki-arrow-right",
      ArrowTwoDiagonals: "ki-arrow-two-diagonals",
      ArrowUpDown: "ki-arrow-up-down",
      ArrowUpLeft: "ki-arrow-up-left",
      ArrowUpRefraction: "ki-arrow-up-refraction",
      ArrowUpRight: "ki-arrow-up-right",
      ArrowUp: "ki-arrow-up",
      ArrowZigzag: "ki-arrow-zigzag",
      ArrowsCircle: "ki-arrows-circle",
      ArrowsLoop: "ki-arrows-loop",
      ArtificialIntelligence: "ki-artificial-intelligence",
      Autobrightness: "ki-autobrightness",
      AvalancheAvax: "ki-avalanche-avax",
      Award: "ki-award",
      Badge: "ki-badge",
      Bandage: "ki-bandage",
      Bank: "ki-bank",
      Barcode: "ki-barcode",
      BasketOk: "ki-basket-ok",
      Basket: "ki-basket",
      Behance: "ki-behance",
      Bill: "ki-bill",
      BinanceUsdBusd: "ki-binance-usd-busd",
      Binance: "ki-binance",
      Bitcoin: "ki-bitcoin",
      BlackDown: "ki-black-down",
      BlackLeftLine: "ki-black-left-line",
      BlackLeft: "ki-black-left",
      BlackRightLine: "ki-black-right-line",
      BlackRight: "ki-black-right",
      BlackUp: "ki-black-up",
      Bluetooth: "ki-bluetooth",
      BookOpen: "ki-book-open",
      BookSquare: "ki-book-square",
      Book: "ki-book",
      CelsiusCel: "ki-celsius-cel",
      Bookmark2: "ki-bookmark-2",
      Bookmark: "ki-bookmark",
      Bootstrap: "ki-bootstrap",
      Briefcase: "ki-briefcase",
      BrifecaseCros: "ki-brifecase-cros",
      BrifecaseTick: "ki-brifecase-tick",
      BrifecaseTimer: "ki-brifecase-timer",
      Brush: "ki-brush",
      BucketSquare: "ki-bucket-square",
      Bucket: "ki-bucket",
      BurgerMenu1: "ki-burger-menu-1",
      BurgerMenu2: "ki-burger-menu-2",
      BurgerMenu3: "ki-burger-menu-3",
      BurgerMenu4: "ki-burger-menu-4",
      BurgerMenu5: "ki-burger-menu-5",
      BurgerMenu6: "ki-burger-menu-6",
      BurgerMenu: "ki-burger-menu",
      Bus: "ki-bus",
      Calculator: "ki-calculator",
      Calculatoror: "ki-calculatoror",
      Calendar2: "ki-calendar-2",
      Calendar8: "ki-calendar-8",
      CalendarAdd: "ki-calendar-add",
      CalendarEdit: "ki-calendar-edit",
      CalendarRemove: "ki-calendar-remove",
      CalendarSearch: "ki-calendar-search",
      CalendarTick: "ki-calendar-tick",
      Calendar: "ki-calendar",
      Call: "ki-call",
      Capsule: "ki-capsule",
      Car: "ki-car",
      Category: "ki-category",
      Cd: "ki-cd",
      "Celsius Cel": "ki-celsius-cel",
      "Chart Line Down 2": "ki-chart-line-down-2",
      "Chart Line Down": "ki-chart-line-down",
      "Chart Line Star": "ki-chart-line-star",
      "Chart Line Up 2": "ki-chart-line-up-2",
      "Chart Line Up": "ki-chart-line-up",
      "Chart Line": "ki-chart-line",
      "Chart Pie 3": "ki-chart-pie-3",
      "Chart Pie 4": "ki-chart-pie-4",
      "Chart Pie Simple": "ki-chart-pie-simple",
      "Chart Pie Too": "ki-chart-pie-too",
      "Chart Simple 2": "ki-chart-simple-2",
      "Chart Simple 3": "ki-chart-simple-3",
      "Chart Simple": "ki-chart-simple",
      Chart: "ki-chart",
      "Check Circle": "ki-check-circle",
      "Check Squared": "ki-check-squared",
      Check: "ki-check",
      Cheque: "ki-cheque",
      Chrome: "ki-chrome",
      Classmates: "ki-classmates",
      Click: "ki-click",
      Clipboard: "ki-clipboard",
      "Cloud Add": "ki-cloud-add",
      "Cloud Change": "ki-cloud-change",
      "Cloud Download": "ki-cloud-download",
      Cloud: "ki-cloud",
      Code: "ki-code",
      Coffee: "ki-coffee",
      "Color Swatch": "ki-color-swatch",
      "Colors Square": "ki-colors-square",
      Compass: "ki-compass",
      "Copy Success": "ki-copy-success",
      Copy: "ki-copy",
      "Courier Express": "ki-courier-express",
      Courier: "ki-courier",
      "Credit Cart": "ki-credit-cart",
      "Cross Circle": "ki-cross-circle",
      "Cross Square": "ki-cross-square",
      Cross: "ki-cross",
      "Crown 2": "ki-crown-2",
      Crown: "ki-crown",
      CSS: "ki-css",
      "Cube 2": "ki-cube-2",
      "Cube 3": "ki-cube-3",
      Cup: "ki-cup",
      Cursor: "ki-cursor",
      Dash: "ki-dash",
      Data: "ki-data",
      "Delete Files": "ki-delete-files",
      "Delete Folder": "ki-delete-folder",
      "Delivery 2": "ki-delivery-2",
      "Delivery 3": "ki-delivery-3",
      "Delivery 24": "ki-delivery-24",
      "Delivery Door": "ki-delivery-door",
      "Delivery Geolocation": "ki-delivery-geolocation",
      "Delivery Time": "ki-delivery-time",
      Delivery: "ki-delivery",
      "Design 1": "ki-design-1",
      "Design 2": "ki-design-2",
      "Desktop Mobile": "ki-desktop-mobile",
      "Devices 2": "ki-devices-2",
      Devices: "ki-devices",
      Diamonds: "ki-diamonds",
      "Directbox Default": "ki-directbox-default",
      Disconnect: "ki-disconnect",
      Discount: "ki-discount",
      Disguise: "ki-disguise",
      Disk: "ki-disk",
      Dislike: "ki-dislike",
      Dj: "ki-dj",
      Document: "ki-document",
      "Double Check": "ki-double-check",
      Dollar: "ki-dollar",
      "Dots Circle Vertical": "ki-dots-circle-vertical",
      "Dots Circle": "ki-dots-circle",
      "Dots Horizontal": "ki-dots-horizontal",
      "Dots Square Vertical": "ki-dots-square-vertical",
      "Dots Square": "ki-dots-square",
      "Dots Vertical": "ki-dots-vertical",
      "Double Check Circle": "ki-double-check-circle",
      "Double Down": "ki-double-down",
      "Double Left Arrow": "ki-double-left-arrow",
      "Double Left": "ki-double-left",
      "Double Right Arrow": "ki-double-right-arrow",
      "Double Right": "ki-double-right",
      "Double Up": "ki-double-up",
      "Down Square": "ki-down-square",
      Down: "ki-down",
      Dribbble: "ki-dribbble",
      Drop: "ki-drop",
      Dropbox: "ki-dropbox",
      "Educare Ekt": "ki-educare-ekt",
      Electricity: "ki-electricity",
      "Electronic Clock": "ki-electronic-clock",
      "Element 1": "ki-element-1",
      "Element 2": "ki-element-2",
      "Element 3": "ki-element-3",
      "Element 4": "ki-element-4",
      "Element 5": "ki-element-5",
      "Element 6": "ki-element-6",
      "Element 7": "ki-element-7",
      "Element 8": "ki-element-8",
      "Element 9": "ki-element-9",
      "Element 10": "ki-element-10",
      "Element 11": "ki-element-11",
      "Element 12": "ki-element-12",
      "Element Equal": "ki-element-equal",
      "Element Plus": "ki-element-plus",
      "Emoji Happy": "ki-emoji-happy",
      "Enjin Coin ENJ": "ki-enjin-coin-enj",
      Ensure: "ki-ensure",
      "Entrance Left": "ki-entrance-left",
      "Entrance Right": "ki-entrance-right",
      Eraser: "ki-eraser",
      Euro: "ki-euro",
      "Exit Down": "ki-exit-down",
      "Exit Left": "ki-exit-left",
      "Exit Right Corner": "ki-exit-right-corner",
      "Exit Right": "ki-exit-right",
      "Exit Up": "ki-exit-up",
      "External Drive": "ki-external-drive",
      "Eye Slash": "ki-eye-slash",
      Eye: "ki-eye",
      "Face ID": "ki-face-id",
      Facebook: "ki-facebook",
      Fasten: "ki-fasten",
      Fatrows: "ki-fatrows",
      Feather: "ki-feather",
      Figma: "ki-figma",
      "File Added": "ki-file-added",
      "File Deleted": "ki-file-deleted",
      "File Down": "ki-file-down",
      "File Left": "ki-file-left",
      "File Right": "ki-file-right",
      "File Sheet": "ki-file-sheet",
      "File Up": "ki-file-up",
      Files: "ki-files",
      "Filter Edit": "ki-filter-edit",
      "Filter Search": "ki-filter-search",
      "Filter Square": "ki-filter-square",
      "Filter Tablet": "ki-filter-tablet",
      "Filter Tick": "ki-filter-tick",
      Filter: "ki-filter",
      "Financial Schedule": "ki-financial-schedule",
      "Fingerprint Scanning": "ki-fingerprint-scanning",
      Flag: "ki-flag",
      "Flash Circle": "ki-flash-circle",
      Flask: "ki-flask",
      Focus: "ki-focus",
      "Folder Added": "ki-folder-added",
      "Folder Down": "ki-folder-down",
      "Folder Up": "ki-folder-up",
      Folder: "ki-folder",
      Frame: "ki-frame",
      "Geolocation Home": "ki-geolocation-home",
      Geolocation: "ki-geolocation",
      Ghost: "ki-ghost",
      Gift: "ki-gift",
      Github: "ki-github",
      Glass: "ki-glass",
      "Google Play": "ki-google-play",
      Google: "ki-google",
      "Graph 2": "ki-graph-2",
      "Graph 3": "ki-graph-3",
      "Graph 4": "ki-graph-4",
      "Graph Up": "ki-graph-up",
      Graph: "ki-graph",
      "Grid 2": "ki-grid-2",
      Grid: "ki-grid",
      Handcart: "ki-handcart",
      Happyemoji: "ki-happyemoji",
      "Heart Circle": "ki-heart-circle",
      Heart: "ki-heart",
      "Home 1": "ki-home-1",
      "Home 2": "ki-home-2",
      "Home 3": "ki-home-3",
      Home: "ki-home",
      HTML: "ki-html",
      Icon: "ki-icon",
      Illustrator: "ki-illustrator",
      "Information 1": "ki-information-1",
      "Information 2": "ki-information-2",
      "Information 3": "ki-information-3",
      "Information 4": "ki-information-4",
      Information: "ki-information",
      Instagram: "ki-instagram",
      Joystick: "ki-joystick",
      "JS 2": "ki-js-2",
      JS: "ki-js",
      Kanban: "ki-kanban",
      "Key Square": "ki-key-square",
      Key: "ki-key",
      Keyboard: "ki-keyboard",
      Laptop: "ki-laptop",
      Laravel: "ki-laravel",
      "Left Square": "ki-left-square",
      Left: "ki-left",
      "Like 2": "ki-like-2",
      "Like Folder": "ki-like-folder",
      "Like Shapes": "ki-like-shapes",
      "Like Tag": "ki-like-tag",
      Like: "ki-like",
      Loading: "ki-loading",
      "Lock 2": "ki-lock-2",
      "Lock 3": "ki-lock-3",
      Lock: "ki-lock",
      Logistic: "ki-logistic",
      "Lots Shopping": "ki-lots-shopping",
      Lovely: "ki-lovely",
      LTS: "ki-lts",
      Magnifier: "ki-magnifier",
      Map: "ki-map",
      Mask: "ki-mask",
      Maximize: "ki-maximize",
      "Medal Star": "ki-medal-star",
      Menu: "ki-menu",
      "Message Add": "ki-message-add",
      "Message Edit": "ki-message-edit",
      "Message Minus": "ki-message-minus",
      "Message Notify": "ki-message-notify",
      "Message Programming": "ki-message-programming",
      "Message Question": "ki-message-question",
      "Message Text 2": "ki-message-text-2",
      "Message Text": "ki-message-text",
      Messages: "ki-messages",
      Microsoft: "ki-microsoft",
      Milk: "ki-milk",
      "Minus Circle": "ki-minus-circle",
      "Minus Folder": "ki-minus-folder",
      "Minus Squared": "ki-minus-squared",
      Minus: "ki-minus",
      Moon: "ki-moon",
      "More 2": "ki-more-2",
      "Mouse Circle": "ki-mouse-circle",
      "Mouse Square": "ki-mouse-square",
      Mouse: "ki-mouse",
      Nexo: "ki-nexo",
      "Night Day": "ki-night-day",
      "Note 2": "ki-note-2",
      Note: "ki-note",
      "Notepad Bookmark": "ki-notepad-bookmark",
      "Notepad Edit": "ki-notepad-edit",
      Notepad: "ki-notepad",
      "Notification 1": "ki-notification-1",
      "Notification Bing": "ki-notification-bing",
      "Notification Circle": "ki-notification-circle",
      "Notification Favorite": "ki-notification-favorite",
      "Notification On": "ki-notification-on",
      "Notification Status": "ki-notification-status",
      Notification: "ki-notification",
      Ocean: "ki-ocean",
      "Office Bag": "ki-office-bag",
      Package: "ki-package",
      Pad: "ki-pad",
      Pails: "ki-pails",
      "Paint Bucket": "ki-paintbucket",
      "Paper Clip": "ki-paper-clip",
      "Paper Plane": "ki-paper-plane",
      "Parcel Tracking": "ki-parcel-tracking",
      Parcel: "ki-parcel",
      "Password Check": "ki-password-check",
      Paypal: "ki-paypal",
      Pencil: "ki-pencil",
      People: "ki-people",
      Percentage: "ki-percentage",
      Phone: "ki-phone",
      Photoshop: "ki-photoshop",
      Picture: "ki-picture",
      Pill: "ki-pill",
      Pin: "ki-pin",
      "Plus Circle": "ki-plus-circle",
      "Plus Squared": "ki-plus-squared",
      Plus: "ki-plus",
      Pointers: "ki-pointers",
      "Price Tag": "ki-price-tag",
      Printer: "ki-printer",
      "Profile Circle": "ki-profile-circle",
      Pulse: "ki-pulse",
      Purchase: "ki-purchase",
      Python: "ki-python",
      "Question 2": "ki-question-2",
      Question: "ki-question",
      "Questionnaire Tablet": "ki-questionnaire-tablet",
      Ranking: "ki-ranking",
      React: "ki-react",
      "Receipt Square": "ki-receipt-square",
      Rescue: "ki-rescue",
      "Right Left": "ki-right-left",
      "Right Square": "ki-right-square",
      Right: "ki-right",
      Rocket: "ki-rocket",
      Route: "ki-route",
      Router: "ki-router",
      "Row Horizontal": "ki-row-horizontal",
      "Row Vertical": "ki-row-vertical",
      "Safe Home": "ki-safe-home",
      Satellite: "ki-satellite",
      "Save 2": "ki-save-2",
      "Save Deposit": "ki-save-deposit",
      "Scan Barcode": "ki-scan-barcode",
      Screen: "ki-screen",
      Scroll: "ki-scroll",
      "Search List": "ki-search-list",
      "Security User": "ki-security-user",
      "Setting 2": "ki-setting-2",
      "Setting 3": "ki-setting-3",
      "Setting 4": "ki-setting-4",
      Setting: "ki-setting",
      Share: "ki-share",
      "Shield Cross": "ki-shield-cross",
      "Shield Search": "ki-shield-search",
      "Shield Slash": "ki-shield-slash",
      "Shield Tick": "ki-shield-tick",
      Shield: "ki-shield",
      Ship: "ki-ship",
      Shop: "ki-shop",
      "Simcard 2": "ki-simcard-2",
      Simcard: "ki-simcard",
      Size: "ki-size",
      Slack: "ki-slack",
      "Slider Horizontal 2": "ki-slider-horizontal-2",
      "Slider Horizontal": "ki-slider-horizontal",
      "Slider Vertical": "ki-slider-vertical",
      Slider: "ki-slider",
      Sms: "ki-sms",
      Snapchat: "ki-snapchat",
      "Social Media": "ki-social-media",
      "Soft 2": "ki-soft-2",
      "Soft 3": "ki-soft-3",
      Soft: "ki-soft",
      "Some Files": "ki-some-files",
      Sort: "ki-sort",
      Speaker: "ki-speaker",
      Spotify: "ki-spotify",
      "Spring Framework": "ki-spring-framework",
      "Square Brackets": "ki-square-brackets",
      Star: "ki-star",
      Status: "ki-status",
      Subtitle: "ki-subtitle",
      Sun: "ki-sun",
      Support: "ki-support",
      Switch: "ki-switch",
      Syringe: "ki-syringe",
      "Tab Tablet": "ki-tab-tablet",
      "Tablet Delete": "ki-tablet-delete",
      "Tablet Down": "ki-tablet-down",
      "Tablet Ok": "ki-tablet-ok",
      "Tablet Text Down": "ki-tablet-text-down",
      "Tablet Text Up": "ki-tablet-text-up",
      "Tablet Up": "ki-tablet-up",
      Tablet: "ki-tablet",
      "Tag Cross": "ki-tag-cross",
      Tag: "ki-tag",
      Teacher: "ki-teacher",
      "Technology 1": "ki-technology-1",
      "Technology 2": "ki-technology-2",
      "Technology 3": "ki-technology-3",
      "Technology 4": "ki-technology-4",
      "Telephone Geolocation": "ki-telephone-geolocation",
      "Test Tubes": "ki-test-tubes",
      "Text Bold": "ki-text-bold",
      "Text Circle": "ki-text-circle",
      "Text Italic": "ki-text-italic",
      "Text Number": "ki-text-number",
      "Text Strikethrough": "ki-text-strikethrough",
      "Text Underline": "ki-text-underline",
      Text: "ki-text",
      "Text Align Center": "ki-textalign-center",
      "Text Align Justify Center": "ki-textalign-justifycenter",
      "Text Align Left": "ki-textalign-left",
      "Text Align Right": "ki-textalign-right",
      Thermometer: "ki-thermometer",
      "Theta Theta": "ki-theta-theta",
      Tiktok: "ki-tiktok",
      Time: "ki-time",
      Timer: "ki-timer",
      "To Left": "ki-to-left",
      "To Right": "ki-to-right",
      "Toggle Off Circle": "ki-toggle-off-circle",
      "Toggle Off": "ki-toggle-off",
      "Toggle On Circle": "ki-toggle-on-circle",
      "Toggle On": "ki-toggle-on",
      "Trash Square": "ki-trash-square",
      Trash: "ki-trash",
      Tree: "ki-tree",
      Trello: "ki-trello",
      TS: "ki-ts",
      Twitch: "ki-twitch",
      Twitter: "ki-twitter",
      "Two Credit Cart": "ki-two-credit-cart",
      Underlining: "ki-underlining",
      "Up Diagonal": "ki-up-diagonal",
      "Up Down": "ki-up-down",
      "Up Square": "ki-up-square",
      Up: "ki-up",
      "Update File": "ki-update-file",
      "Update Folder": "ki-update-folder",
      "User Edit": "ki-user-edit",
      "User Square": "ki-user-square",
      "User Tick": "ki-user-tick",
      User: "ki-user",
      Users: "ki-users",
      Verify: "ki-verify",
      "Vibe Vibe": "ki-vibe-vibe",
      Virus: "ki-virus",
      Vue: "ki-vue",
      Vuesax: "ki-vuesax",
      Wallet: "ki-wallet",
      "Wanchain Wan": "ki-wanchain-wan",
      Watch: "ki-watch",
      Whatsapp: "ki-whatsapp",
      "Wifi Home": "ki-wifi-home",
      "Wifi Square": "ki-wifi-square",
      Wifi: "ki-wifi",
      Wireframe: "ki-wireframe",
      Wlan: "ki-wlan",
      Wrench: "ki-wrench",
      Xiaomi: "ki-xaomi",
      XD: "ki-xd",
      XMR: "ki-xmr",
      Yii: "ki-yii",
      YouTube: "ki-youtube",
    },
  },
  defaultVariants: {
    style: "Duotone",
  },
});

interface TKeenIconsProps {
  className?: string;
  icon?: VariantProps<typeof iconVariants>["icon"];
  style?: VariantProps<typeof iconVariants>["style"];
}

const KeenIcons = forwardRef<HTMLElement, TKeenIconsProps>(
  ({ icon, style, className, ...props }, ref) => (
    <i
      ref={ref}
      className={cn(iconVariants({ style, icon }), className)}
      {...props}
    />
  )
);
KeenIcons.displayName = "KeenIcons";
export { KeenIcons };
